version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    secrets:
      - mariadb_root_password
      - mariadb_user_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    secrets:
      - mariadb_root_password
      - mariadb_user_password
      - wordpress_admin_password
      - wordpress_user_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    env_file: .env
    networks:
      - inception
    restart: unless-stopped

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    env_file: .env
    volumes:
      - wordpress_data:/var/www/wordpress
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    secrets:
      - ftp_password
    networks:
      - inception
    restart: unless-stopped

  static_website:
    build: ./requirements/bonus/static_website
    container_name: static_website
    ports:
      - "8080:80"
    networks:
      - inception
    restart: unless-stopped

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    ports:
      - "8081:80"
    networks:
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped

  cadvisor:
    build: ./requirements/bonus/cAdvisor
    container_name: cadvisor
    ports:
      - "8082:8082"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inception
    restart: unless-stopped

secrets:
  mariadb_root_password:
    file: ./secrets/db_root_password.txt
  mariadb_user_password:
    file: ./secrets/db_password.txt
  wordpress_admin_password:
    file: ./secrets/wp_admin_password.txt
  wordpress_user_password:
    file: ./secrets/wp_user_password.txt
  ftp_password:
    file: ./secrets/ftp_password.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  inception:
    driver: bridge
